const HIGHLIGHTJS_STYLES = [
{ label:"A11y-light"				, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/a11y-light.min.css"},
{ label:"Agate"						, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/agate.min.css"},
{ label:"An-old-hope"				, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/an-old-hope.min.css"},
{ label:"Androidstudio"				, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/androidstudio.min.css"},
{ label:"Arduino-light"				, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/arduino-light.min.css"},
{ label:"Arta"						, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/arta.min.css"},
{ label:"Ascetic"					, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/ascetic.min.css"},
{ label:"Atelier-cave-dark"			, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-cave-dark.min.css"},
{ label:"Atelier-cave-light"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-cave-light.min.css"},
{ label:"Atelier-dune-dark"			, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-dune-dark.min.css"},
{ label:"Atelier-dune-light"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-dune-light.min.css"},
{ label:"Atelier-estuary-dark"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-estuary-dark.min.css"},
{ label:"Atelier-estuary-light"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-estuary-light.min.css"},
{ label:"Atelier-forest-dark"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-forest-dark.min.css"},
{ label:"Atelier-forest-light"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-forest-light.min.css"},
{ label:"Atelier-heath-dark"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-heath-dark.min.css"},
{ label:"Atelier-heath-light"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-heath-light.min.css"},
{ label:"Atelier-lakeside-dark"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-lakeside-dark.min.css"},
{ label:"Atelier-plateau-dark"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-plateau-dark.min.css"},
{ label:"Atelier-savanna-dark"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-savanna-dark.min.css"},
{ label:"Atelier-savanna-light"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-savanna-light.min.css"},
{ label:"Atelier-seaside-dark"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-seaside-dark.min.css"},
{ label:"Atelier-seaside-light"		, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atelier-seaside-light.min.css"},
{ label:"Atom-one-dark-reasonable"	, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atom-one-dark-reasonable.min.css"},
{ label:"Atom-one-dark"				, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atom-one-dark.min.css"},
{ label:"Atom-one-light"			, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/atom-one-light.min.css"},
{ label:"Brown-paper"				, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/brown-paper.min.css"},
{ label:"Codepen-embed"				, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/codepen-embed.min.css"},
{ label:"Darcula"					, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/darcula.min.css"},
{ label:"Dark"						, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/dark.min.css"},
{ label:"Github-gist"				, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/github-gist.min.css"},
{ label:"Github"					, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/github.min.css"},
{ label:"GRAYSCALE"					, value: "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.14.2/build/styles/grayscale.min.css"},

];




